name: Deploy HTML to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: Test    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'  # Path to your static web files (e.g., .html, .css, .js)
  # No need for NODE_VERSION since you're not using Node.js

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}   # Your Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Store publish profile as a GitHub secret
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  # Path to your static files (default to root folder)
